# Generated by Django 5.1.15 on 2026-06-14 16:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('height_cm', models.PositiveIntegerField(default=170, help_text='Height in centimeters', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('arm_length_cm', models.PositiveIntegerField(default=60, help_text='Arm length (draw length) in centimeters', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)])),
                ('strength_lbs', models.PositiveIntegerField(default=25, help_text='Comfortable draw weight in lbs (20=light, 40+=heavy)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('age', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('adept', 'Adept'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20)),
                ('accuracy_pct', models.FloatField(default=50.0, help_text='Percentage of shots hitting the centre (0-100%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_vip', models.BooleanField(default=False, help_text='VIP members: unlimited bows + bow suggestion + bow generation')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='VIPMember',
            fields=[
            ],
            options={
                'verbose_name': 'VIP Member',
                'verbose_name_plural': 'VIP Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('club_app.clubmember',),
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bow_type', models.CharField(choices=[('longbow', 'Long Bow'), ('shortbow', 'Short Bow'), ('recurve', 'Recurve Bow'), ('compound', 'Compound Bow'), ('crossbow', 'Crossbow')], default='recurve', max_length=20)),
                ('draw_weight_lbs', models.PositiveIntegerField(help_text='Draw weight (tension) in pounds', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('length_cm', models.PositiveIntegerField(help_text='Bow length in centimeters', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('material', models.CharField(choices=[('wood', 'Wood'), ('composite', 'Composite'), ('carbon', 'Carbon Fiber'), ('fiberglass', 'Fiberglass'), ('hybrid', 'Hybrid (Wood + Composite)')], default='wood', max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this bow')),
                ('added_by', models.ForeignKey(blank=True, help_text='Member who added this bow to the database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_bows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bow',
                'verbose_name_plural': 'Bows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberBow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary/favourite bow')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('bow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bow_members', to='club_app.bow')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_bows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Bow',
                'verbose_name_plural': 'Member Bows',
                'ordering': ['-is_primary', 'date_added'],
                'unique_together': {('member', 'bow')},
            },
        ),
    ]
